import { calculateSunTimes, formatTime, getMoonData, calculateMilkyWay, calculateAstronomicalEvents } from './astronomy.js';

const $ = id => document.getElementById(id);
function localDateISO(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function paramsState(){const p=new URLSearchParams(location.search);return {lat:Number(p.get('lat')),lon:Number(p.get('lon')),date:p.get('date')||localDateISO(),name:p.get('name')||'Ubicación seleccionada'};}
function fmtTime(v){return v?formatTime(v):'N/D'}
function updateLinks(){const lat=Number($('astro-lat').value),lon=Number($('astro-lon').value),date=$('astro-date').value,name=encodeURIComponent($('astro-location').value||'Ubicación astronómica'); const q=`?lat=${encodeURIComponent(lat)}&lon=${encodeURIComponent(lon)}&date=${encodeURIComponent(date)}&name=${name}`; $('photo-link').href=`index.html${q}`; $('back-photo').href=`index.html${q}`;}
function render(){
 const lat=Number($('astro-lat').value),lon=Number($('astro-lon').value),date=$('astro-date').value;
 if(!Number.isFinite(lat)||!Number.isFinite(lon)||!date){$('astro-status').textContent='Faltan datos';return;}
 const sun=calculateSunTimes(date,lat,lon); const moon=getMoonData(date,lat,lon); const mw=calculateMilkyWay(date,lat,lon,sun,moon); const events=calculateAstronomicalEvents(date,lat,lon);
 $('moon-info').innerHTML=`<div class="astro-main"><span class="astro-icon moon">${moon.icon}</span><div><span class="astro-kicker">Fase lunar</span><strong>${moon.name}</strong><span class="astro-muted">${moon.illuminationPercent}% iluminada · ${moon.waxing?'creciente':'menguante'}</span></div></div><div class="astro-stats"><div><span>Salida</span><strong>${fmtTime(moon.rise)}</strong></div><div><span>Puesta</span><strong>${fmtTime(moon.set)}</strong></div><div><span>Distancia</span><strong>${Number.isFinite(moon.distance)?Math.round(moon.distance).toLocaleString('es-ES')+' km':'N/D'}</strong></div><div><span>Altura · 12h</span><strong>${Number.isFinite(moon.altitude)?Math.round(moon.altitude*180/Math.PI)+'°':'N/D'}</strong></div></div>`;
 $('milky-way-info').innerHTML=`<div class="astro-main"><span class="astro-icon">🌌</span><div><span class="astro-kicker">Visibilidad fotográfica</span><strong>${mw.score}/100</strong><span class="astro-muted">${mw.label}</span></div></div><div class="astro-stats"><div><span>Ventana</span><strong>${mw.start&&mw.end?fmtTime(mw.start)+'–'+fmtTime(mw.end):'N/D'}</strong></div><div><span>Máxima altura</span><strong>${Number.isFinite(mw.maxAltitudeDeg)?Math.round(mw.maxAltitudeDeg)+'°':'N/D'}</strong></div><div><span>Mejor momento</span><strong>${fmtTime(mw.bestTime)}</strong></div><div><span>Azimut</span><strong>${Number.isFinite(mw.bestAzimuthDeg)?Math.round(mw.bestAzimuthDeg)+'°':'N/D'}</strong></div></div><p class="astro-note">Estimación astronómica para fotografía nocturna; la nubosidad real debe comprobarse en la página de Fotografía.</p>`;
 $('astro-events').innerHTML=events.length?events.map(e=>`<article class="astro-event"><strong>${e.icon||'🔭'} ${e.title}</strong><span>${e.description||''}</span><small>${e.time?fmtTime(e.time):e.dateLabel||date}</small></article>`).join(''):'<div class="empty">No hay eventos destacados calculados para esta fecha.</div>';
 updateLinks(); $('astro-status').textContent=`Actualizado · ${$('astro-location').value||'Ubicación'} · ${date}`;
}
const st=paramsState(); if(Number.isFinite(st.lat))$('astro-lat').value=st.lat; if(Number.isFinite(st.lon))$('astro-lon').value=st.lon; $('astro-date').value=st.date; $('astro-location').value=st.name;
$('astro-update').addEventListener('click',render); ['astro-lat','astro-lon','astro-date','astro-location'].forEach(id=>$(id).addEventListener('change',render)); render();
